[package]
name = "remote-mouse"
version = "0.1.0"
authors = ["Christopher Head"]
edition = "2021"
description = "A WebSocket endpoint that receives mouse events and drives an X display."
repository = "https://gitlab.com/Hawk777/remote-mouse"
license = "GPL-3.0-only"
keywords = ["control", "mobile", "mouse", "remote"]
categories = ["web-programming::websocket"]

[dependencies.anyhow]
version = "^1.0.75"

[dependencies.clap]
features = ["derive", "wrap_help"]
version = "^4.4.10"

[dependencies.env_logger]
default-features = false
version = "^0.11.0"

[dependencies.futures-util]
default-features = false
version = "^0.3.29"

[dependencies.libc]
version = "^0.2.150"

[dependencies.log]
features = ["std"]
version = "^0.4.20"

[dependencies.socket2]
version = "^0.6.0"

[dependencies.tokio]
features = ["io-util", "macros", "net", "rt", "signal", "sync", "time"]
version = "^1.34"

[dependencies.tokio-tungstenite]
default-features = false
features = ["handshake"]
version = "^0.24.0"

[dependencies.tokio-util]
features = ["codec", "net"]
version = "^0.7.10"

[dependencies.x11rb]
features = ["xtest"]
version = "^0.13.1"

[lints.clippy]
allow-attributes-without-reason = { level = "warn", priority = 1 }
cargo = "warn"
cast-precision-loss = { level = "allow", priority = 1 }
multiple-crate-versions = { level = "allow", priority = 1 }
pedantic = "warn"
# log macro logging should be used instead.
print-stderr = { level = "deny", priority = 1 }
print-stdout = { level = "deny", priority = 1 }
tabs-in-doc-comments = { level = "allow", priority = 1 }  # Nope, tabs thanks.

[lints.rust]
future-incompatible = "warn"
macro-use-extern-crate = "warn"
meta-variable-misuse = "warn"
missing-abi = "warn"
missing-copy-implementations = "warn"
missing-docs = "warn"
non-local-definitions = "warn"
nonstandard-style = "warn"
redundant-lifetimes = "warn"
rust-2018-idioms = "warn"
single-use-lifetimes = "warn"
trivial-casts = "warn"
trivial-numeric-casts = "warn"
unit-bindings = "warn"
unsafe-op-in-unsafe-fn = "warn"
unused = "warn"
unused-crate-dependencies = "warn"
unused-import-braces = "warn"
unused-lifetimes = "warn"
unused-qualifications = "warn"
warnings = "warn"

[lints.rustdoc]
all = "warn"
